export const PRODUCTS = [
  {
    id: "github-marker",
    visible: true,
    name: "Github Marker",
    shortDescription:
      "A Chrome Extention to Favorite, Bookmark & Mark link as Read in Github",
    productPath: "/products/github-marker",
    description:
      "There are a lot of links provided on Github pages. Some might need to be marked as read, some might be amazing & some you would love to read it later. Github Marker does exactly that.<br/>The extension provides 3 options attached to every link found on Github related pages/URLs:<br/>1. Mark as Read/Unread <br/>2. Favorite/Un-Favorite a link<br/>3. Bookmark/Unbookmark a link",
    logo: "",
    image: "",
    gallery: [],
    video: "",
    url: "",
    download:
      "https://chrome.google.com/webstore/detail/github-marker/imjdbnnpnohgcdbpgnidgolnamoghpoo?hl=en",
    publicURL: "",
    keywords: [],
  },
  {
    id: "note-box",
    visible: true,
    name: "Note Box",
    shortDescriptionV1: "A Chrome extension to store notes for every domain",
    shortDescription: "A chrome extension to add notes/todos based on URL",
    productPath: "/products/note-box",
    description:
      "A Chrome Extension that provides an environment for every domain/URL. Revisit the notes when back to that URL or access it from `Homepage`. <br/> No Login/Signup. <br/>All the notes are stored in the browser memory.",
    logo: "",
    image: "",
    gallery: [],
    video: "https://youtu.be/fX3IKhiEz1s",
    url: "",
    download:
      "https://chrome.google.com/webstore/detail/note-box/mbbajjgefpenmkkhcnmmnoodlbcbfnmp",
    publicURL: "",
    keywords: [],
  },
  {
    id: "file-ops",
    visible: true,
    name: "File Ops",
    shortDescription: "Easily tag/alias files & quick switch between files.",
    productPath: "/products/file-ops",
    description: "",
    logo: "",
    image: "",
    gallery: [],
    video: "https://youtu.be/ze9KtYe3f48",
    url: "",
    download:
      "https://marketplace.visualstudio.com/items?itemName=mehullakhanpal.file-ops",
    publicURL: "",
    keywords: [],
  },
  {
    id: "dot",
    visible: false,
    name: "DOT",
    shortDescription: "",
    productPath: "/products/dot",
    description:
      "Sometimes there are files which have the same names. ex. index.js. File Ops helps in `tagging` or `aliasing` files. These files can be Viewed & Opened from the tree view or using commands. Another feature is to be able to quickly switch between example.js and example.css. ",
    logo: "",
    image: "",
    gallery: [],
    video: "",
    url: "",
    download: "",
    publicURL: "",
    keywords: [],
  },
  {
    id: "react-ui",
    visible: false,
    name: "React UI",
    shortDescription: "",
    productPath: "/products/react-ui",
    description: "",
    logo: "",
    image: "",
    gallery: [],
    video: "",
    url: "",
    download: "",
    publicURL: "",
    keywords: [],
  },
  {
    id: "atom",
    visible: false,
    name: "Atom",
    shortDescription: "",
    productPath: "/products/atom",
    description: "",
    logo: "",
    image: "",
    gallery: [],
    video: "",
    url: "",
    download: "",
    publicURL: "",
    keywords: [],
  },
];
