export const PRODUCTS = [
  {
    id: "github-marker",
    name: "Github Marker",
    shortDescription: "Mark links as read, favorite or bookmark in github",
    productPath: "/products/github-marker",
    description: "",
    image: "",
    video: "",
    url: "",
    download: "",
  },
  {
    id: "dot",
    name: "DOT",
    shortDescription: "",
    productPath: "/products/dot",
    description: "",
    image: "",
    video: "",
    url: "",
    download: "",
  },
  {
    id: "note-box",
    name: "Note Box",
    shortDescription: "",
    productPath: "/products/note-box",
    description: "",
    image: "",
    video: "",
    url: "",
    download: "",
  },
];
